# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=255)),
                ('noted', models.TextField(null=True)),
                ('img_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
