# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depts',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('work_id', models.CharField(max_length=20, null=True)),
                ('pki_id', models.CharField(max_length=50, null=True)),
                ('id_card', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
