# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It_types',
            fields=[
                ('type_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('rfid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('it_type', models.CharField(max_length=30, null=True)),
                ('sn', models.CharField(max_length=50, null=True)),
                ('dept', models.CharField(max_length=30, null=True)),
                ('user', models.CharField(max_length=10, null=True)),
                ('time', models.DateField(null=True)),
            ],
        ),
    ]
