# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('authors', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=30)),
                ('site_address', models.CharField(max_length=200)),
                ('word_count', models.IntegerField()),
                ('pic_count', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('privilege', models.CharField(max_length=100)),
            ],
        ),
    ]
