# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=14)),
                ('ip_addr', models.CharField(max_length=14)),
                ('vlan_id', models.CharField(max_length=5)),
                ('dept', models.CharField(max_length=20)),
                ('noted', models.CharField(max_length=100)),
            ],
        ),
    ]
