# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_names',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
